### ISSUE TITLE
logo design for GeoQuiz

### ISSUE THREAD

**Issue by hafizahmmed** [hexzha/GeoQuiz#2]
Hello,
Good Day, i make a logo icon for your project. If you want to use this logo in your project, then comment below, I will give you the source file. And if you want a change, then tell me I will change.It's totally free for open source project. 

![geoquiz-01](https://user-images.githubusercontent.com/38810169/42732806-1f295a60-8849-11e8-918b-d9a07897c0c1.jpg)

**Comment by hexzha** [comment]
Sure. Thanks for reaching out.

**Comment by hexzha** [comment]
Still interested in letting me use the logo? @hafizahmmed

**Comment by hexzha** [comment]
I'm going to close this for now. Let me know if you're still interested. @hafizahmmed
